---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: enough-recipes-cert
spec:
  commonName: enough.recipes
  dnsNames:
  - enough.recipes
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: enough-recipes-tls
