---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/vultr-loadbalancer-https-ports: "443"
    service.beta.kubernetes.io/vultr-loadbalancer-ssl: "ssl-secret"
    service.beta.kubernetes.io/vultr-loadbalancer-ssl-pass-through: "false"
    service.beta.kubernetes.io/vultr-loadbalancer-ssl-redirect: "true"
  name: enough-recipes-lb
  namespace: enough-recipes
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      name: "http"
    - port: 443
      name: "https"
      targetPort: 80

