---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f../docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app
    app: app
  name: app
  namespace: enough-recipes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f../docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app
        app: app
    spec:
      imagePullSecrets:
        - name: dr
      containers:
        - args:
            - poetry
            - run
            - gunicorn
            - --bind=0.0.0.0:80
            - --access-logfile=-
            # - --bind=0.0.0.0:443
            # - --keyfile=/etc/secrets/ssl_key
            # - --certfile=/etc/secrets/ssl_cert
            - --threads=4
            - enough_recipes.wsgi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ersecrets
                  key: database_url
                  optional: false
          image: relwell/enough-recipes:latest
          imagePullPolicy: Always
          name: app
          volumeMounts:
            - name: secrets
              mountPath: /etc/secrets
          ports:
            - containerPort: 80
              name: "http"
          resources: {}
          tty: true
          workingDir: /usr/src/app
          livenessProbe:
            httpGet:
              # scheme: HTTPS
              # path: /
              # port: 443
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
      restartPolicy: Always
      volumes:
        - name: secrets
          secret:
            secretName: ersecrets
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: enough-recipes
  labels:
    app: app-svc
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: "http"
