---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: enough-recipes
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: relwell/enough-recipes-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 1
      imagePullSecrets:
        - name: dr
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: enough-recipes
  labels:
    app: nginx-svc
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: "http"
